Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7147400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7147d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70eb700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70f30d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70ebd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70eb340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7134ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7147790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70f3a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70fd3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae71479a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7134b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70f3610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70f3640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70fda00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae71013a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7134bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae70fd8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7147f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2ae7147d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
STOP
